easy_admin:
  entities:
    Image:
      class: App\Entity\Image
      list:
        actions:
          - {name: 'edit', icon: 'paint-brush', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        # item_permission: 'ROLE_ADMIN'
        fields: ['name','poster', {property: 'poster', type: 'image', base_path: '%upload_directory%'}]
      form:
        fields:
          - {property: 'name', label: "Nom de l'image"}
          - {property: 'project', label: 'Projet'}
          - {property: 'posterFile', type: 'vich_image', base_path: '%upload_directory%', label: 'Image'}