easy_admin:
  entities:
    User:
      class: App\Entity\User
      list:
        actions:
          - {name: 'edit', icon: 'paint-brush', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        # item_permission: 'ROLE_ADMIN'
      form:
        fields:
          - {property: 'email', label: 'Email'}
          - {property: 'password', label: 'Mot de passe'}
          - {property: 'role', label: 'Rôle'}
